version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: provisioning/dev/Dockerfile
    image: random_lunch
    container_name: random_lunch_app
    ports:
      - 3000:3000
    volumes:
      - ./:/var/opt/app
